name: GitHub Actions Demo
run-name: ${{ github.actor }} is the one testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
      uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'my_db'
          postgresql user: 'test_user'
          postgresql password: 'test_password'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: PGDATABASE=nc_news_test PGUSER=test_user PGPASSWORD=test_password npm t
