name: GitHub Actions Demo

on:
  pull_request:
    branches:
      -main
      
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'Hello there!'

   util-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: npm ci
      _ name: Test utils
        run: npm run test-utils


    app-tests:
    needs: util-tests
    runs-on: ubuntu-latest
    steps:
      - name: Test app
        uses: npm test