name: GitHub Actions Demo

on:
  pull_request:
    branches:
      - main

jobs:
  util-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: npm ci

      - name: Test utils
        run: npm run test-utils
        
  app-tests:
    needs: util-tests
    runs-on: ubuntu-latest
    steps:
      - name: Test app
        run: npm test
