name: GitHub Actions Demo
run-name: ${{ github.actor }} is the one testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - main
jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
      uses: eacho 'Hello there'

   util-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: npm ci
      _ name: Test utils
        run: npm run test-utils


    app-tests:
    needs: util-tests
    runs-on: ubuntu-latest
    steps:
      - name: Test app
        uses: npm test